from app.schemas.common import ApiResponse
from app.schemas.post import (
    PostCreateRequest,
    PostDeletePayload,
    PostDeleteRequest,
    PostDetailPayload,
    PostsPayload,
    PostWritePayload,
    PostWriteRequest,
)
from app.schemas.post_tags import (
    PostTagDuplicatePayload,
    PostTagDeletePayload,
    PostTagDeleteRequest,
    PostTagPayload,
    PostTagsPayload,
    PostTagUpdateRequest,
    PostTagUpsertManyRequest,
)
from app.schemas.projects import ProjectDetailPayload, ProjectsPayload
from app.schemas.locales import (
    LocaleCreateRequest,
    LocalePayload,
    LocaleUpdateRequest,
)
from app.schemas.site_settings import (
    SiteSettingCreateRequest,
    SiteSettingDeletePayload,
    SiteSettingDeleteRequest,
    SiteSettingPayload,
    SiteSettingsPayload,
    SiteSettingUpdateByKeyRequest,
    SiteSettingUpdateRequest,
)
from app.schemas.site_navigation import (
    SiteNavigationCreateRequest,
    SiteNavigationDeletePayload,
    SiteNavigationDeleteRequest,
    SiteNavigationPayload,
    SiteNavigationsPayload,
    SiteNavigationUpdateRequest,
    SiteNavigationUpsertManyRequest,
)
from app.schemas.site_config_categories import (
    SiteConfigCategoriesPayload,
    SiteConfigCategoryCreateRequest,
    SiteConfigCategoryPayload,
    SiteConfigCategoryUpsertManyRequest,
)

__all__ = [
    "ApiResponse",
    "PostCreateRequest",
    "PostDeletePayload",
    "PostDeleteRequest",
    "PostDetailPayload",
    "PostsPayload",
    "PostWritePayload",
    "PostWriteRequest",
    "PostTagDeletePayload",
    "PostTagDeleteRequest",
    "PostTagDuplicatePayload",
    "PostTagPayload",
    "PostTagsPayload",
    "PostTagUpdateRequest",
    "PostTagUpsertManyRequest",
    "ProjectDetailPayload",
    "ProjectsPayload",
    "LocaleCreateRequest",
    "LocalePayload",
    "LocaleUpdateRequest",
    "SiteSettingCreateRequest",
    "SiteSettingDeletePayload",
    "SiteSettingDeleteRequest",
    "SiteSettingPayload",
    "SiteSettingsPayload",
    "SiteSettingUpdateByKeyRequest",
    "SiteSettingUpdateRequest",
    "SiteNavigationCreateRequest",
    "SiteNavigationDeletePayload",
    "SiteNavigationDeleteRequest",
    "SiteNavigationPayload",
    "SiteNavigationsPayload",
    "SiteNavigationUpdateRequest",
    "SiteNavigationUpsertManyRequest",
    "SiteConfigCategoriesPayload",
    "SiteConfigCategoryCreateRequest",
    "SiteConfigCategoryPayload",
    "SiteConfigCategoryUpsertManyRequest",
]
