from app.schemas.common import ApiResponse
from app.schemas.search import SearchGroupPayload, SearchItemPayload, SearchPayload
from app.schemas.post import (
    PostCreateRequest,
    PostDeletePayload,
    PostDeleteRequest,
    PostDetailPayload,
    PostsPayload,
    PostWritePayload,
    PostWriteRequest,
)
from app.schemas.post_tags import (
    PostTagDuplicatePayload,
    PostTagDeletePayload,
    PostTagDeleteRequest,
    PostTagPayload,
    PostTagsPayload,
    PostTagUpdateRequest,
    PostTagUpsertManyRequest,
)
from app.schemas.projects import ProjectDetailPayload, ProjectsPayload
from app.schemas.locales import (
    LocaleCreateRequest,
    LocalePayload,
    LocalesPayload,
    LocaleUpdateRequest,
)
from app.schemas.site_settings import (
    SiteSettingCreateRequest,
    SiteSettingDeletePayload,
    SiteSettingDeleteRequest,
    SiteSettingPayload,
    SiteSettingsPayload,
    SiteSettingUpdateByKeyRequest,
    SiteSettingUpdateRequest,
)
from app.schemas.site_navigation import (
    SiteNavigationCreateRequest,
    SiteNavigationDeletePayload,
    SiteNavigationDeleteRequest,
    SiteNavigationPayload,
    SiteNavigationsPayload,
    SiteNavigationUpdateRequest,
    SiteNavigationUpsertManyRequest,
)
from app.schemas.site_config_categories import (
    SiteConfigCategoriesPayload,
    SiteConfigCategoryCreateRequest,
    SiteConfigCategoryPayload,
    SiteConfigCategoryUpsertManyRequest,
)
from app.schemas.static_content import (
    StaticContentCreateRequest,
    StaticContentDeletePayload,
    StaticContentDeleteRequest,
    StaticContentPayload,
    StaticContentsPayload,
    StaticContentUpdateRequest,
    StaticContentUpsertByKeyRequest,
)
from app.schemas.static_content_categories import (
    StaticContentCategoriesPayload,
    StaticContentCategoryCreateRequest,
    StaticContentCategoryPayload,
    StaticContentCategoryUpsertManyRequest,
)

__all__ = [
    "ApiResponse",
    "SearchGroupPayload",
    "SearchItemPayload",
    "SearchPayload",
    "PostCreateRequest",
    "PostDeletePayload",
    "PostDeleteRequest",
    "PostDetailPayload",
    "PostsPayload",
    "PostWritePayload",
    "PostWriteRequest",
    "PostTagDeletePayload",
    "PostTagDeleteRequest",
    "PostTagDuplicatePayload",
    "PostTagPayload",
    "PostTagsPayload",
    "PostTagUpdateRequest",
    "PostTagUpsertManyRequest",
    "ProjectDetailPayload",
    "ProjectsPayload",
    "LocaleCreateRequest",
    "LocalePayload",
    "LocalesPayload",
    "LocaleUpdateRequest",
    "SiteSettingCreateRequest",
    "SiteSettingDeletePayload",
    "SiteSettingDeleteRequest",
    "SiteSettingPayload",
    "SiteSettingsPayload",
    "SiteSettingUpdateByKeyRequest",
    "SiteSettingUpdateRequest",
    "SiteNavigationCreateRequest",
    "SiteNavigationDeletePayload",
    "SiteNavigationDeleteRequest",
    "SiteNavigationPayload",
    "SiteNavigationsPayload",
    "SiteNavigationUpdateRequest",
    "SiteNavigationUpsertManyRequest",
    "SiteConfigCategoriesPayload",
    "SiteConfigCategoryCreateRequest",
    "SiteConfigCategoryPayload",
    "SiteConfigCategoryUpsertManyRequest",
    "StaticContentCreateRequest",
    "StaticContentDeletePayload",
    "StaticContentDeleteRequest",
    "StaticContentPayload",
    "StaticContentsPayload",
    "StaticContentUpdateRequest",
    "StaticContentUpsertByKeyRequest",
    "StaticContentCategoriesPayload",
    "StaticContentCategoryCreateRequest",
    "StaticContentCategoryPayload",
    "StaticContentCategoryUpsertManyRequest",
]
