import { defineDocumentType, makeSource } from 'contentlayer2/source-files'
import fs from 'fs'

// Post 文档（保持不变）
export const Post = defineDocumentType(() => ({
  name: 'Post',
  filePathPattern: `**/*.mdx`,
  contentType: 'mdx',
  fields: {
    title: { type: 'string', required: true },
    date: { type: 'date', required: true },
    description: { type: 'string' },
    tags: { type: 'list', of: { type: 'string' } },
    published: { type: 'boolean', default: true },
    featured: { type: 'boolean', default: false },
    updatedAt: { type: 'date' },
    locale: { type: 'string', default: 'zh' },
    originalSlug: { type: 'string' },
  },
  computedFields: {
    slug: {
      type: 'string',
      resolve: (post) => {
        const pathParts = post._raw.flattenedPath.split('/')
        return pathParts[pathParts.length - 1].replace('.mdx', '')
      },
    },
    locale: {
      type: 'string',
      resolve: (post) => {
        const pathParts = post._raw.flattenedPath.split('/')
        return pathParts[0] || 'zh'
      },
    },
    url: {
      type: 'string',
      resolve: (post) => {
        const pathParts = post._raw.flattenedPath.split('/')
        const slug = pathParts[pathParts.length - 1].replace('.mdx', '')
        return `/posts/${slug}`
      },
    },
    formattedTags: {
      type: 'list',
      of: { type: 'string' },
      resolve: (post) => {
        if (!post.tags) return []
        
        // 处理 PlainArr 对象，转换为普通数组
        const tagsArray = Array.isArray(post.tags) ? post.tags : Array.from(post.tags) as string[]
        
        const formatTag = (tag: string): string => {
          return tag
            .split('.')
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join('')
        }
        
        return tagsArray.map(formatTag)
      },
    },
  },
}))

// makeSource
export default makeSource({
  contentDirPath: './content',
  documentTypes: [Post],
  disableImportAliasWarning: true,

  async onSuccess(getData) {
    const { allPosts } = await getData()
    const tags = new Set<string>()

    // 收集所有标签
    allPosts.flatMap((post) => post.formattedTags || []).forEach((t) => tags.add(t))

    const tagArray = Array.from(tags).filter(tag => !!tag).sort()

    const jsonPath = '.contentlayer/generated/tagList.json'
    const mjsPath = '.contentlayer/generated/tagList.mjs'
    const indexPath = '.contentlayer/generated/index.mjs'

    // 1. 写 JSON
    fs.writeFileSync(jsonPath, JSON.stringify(tagArray, null, 2))

    // 2. 写 MJS
    const mjsContent = `// Auto-generated by Contentlayer on build
export const tagList = ${JSON.stringify(tagArray, null, 2)};
`
    fs.writeFileSync(mjsPath, mjsContent)

    // 3. 更新 index.mjs 以导出 tagList
    const indexContent = `// NOTE This file is auto-generated by Contentlayer

export { isType } from 'contentlayer2/client'

// NOTE During development Contentlayer imports from \`.mjs\` files to improve HMR speeds.
// During (production) builds Contentlayer it imports from \`.json\` files to improve build performance.
import allPosts from './Post/_index.json' assert { type: 'json' }

export { allPosts }

export const allDocuments = [...allPosts]

// 导出标签列表
export { tagList } from './tagList.mjs'
`
    fs.writeFileSync(indexPath, indexContent)

    // 4. 更新 index.d.ts 以包含 tagList 类型声明
    const indexDtsPath = '.contentlayer/generated/index.d.ts'
    const indexDtsContent = `// NOTE This file is auto-generated by Contentlayer

import { Post, DocumentTypes, DataExports } from './types'
import { SourceProvideSchemaErrorJSON, SourceFetchDataErrorJSON } from 'contentlayer2/core'

export * from './types'

export declare const allPosts: Post[]

export declare const allDocuments: DocumentTypes[]

export declare const tagList: string[]
`
    fs.writeFileSync(indexDtsPath, indexDtsContent)

    console.log(`✅ Generated ${tagArray.length} tags → ${jsonPath}, ${mjsPath}`)
  },
})
