import { defineDocumentType, makeSource } from 'contentlayer2/source-files'
import fs from 'fs'

// Post 文档（保持不变）
export const Post = defineDocumentType(() => ({
  name: 'Post',
  filePathPattern: `**/*.mdx`,
  contentType: 'mdx',
  fields: {
    title: { type: 'string', required: true },
    date: { type: 'date', required: true },
    description: { type: 'string' },
    tags: { type: 'list', of: { type: 'string' } },
    published: { type: 'boolean', default: true },
    featured: { type: 'boolean', default: false },
    updatedAt: { type: 'date' },
    locale: { type: 'string', default: 'zh' },
    originalSlug: { type: 'string' },
  },
  computedFields: {
    slug: {
      type: 'string',
      resolve: (post) => {
        const pathParts = post._raw.flattenedPath.split('/')
        return pathParts[pathParts.length - 1].replace('.mdx', '')
      },
    },
    locale: {
      type: 'string',
      resolve: (post) => {
        const pathParts = post._raw.flattenedPath.split('/')
        return pathParts[0] || 'zh'
      },
    },
    url: {
      type: 'string',
      resolve: (post) => {
        const pathParts = post._raw.flattenedPath.split('/')
        const slug = pathParts[pathParts.length - 1].replace('.mdx', '')
        return `/posts/${slug}`
      },
    },
  },
}))

// makeSource
export default makeSource({
  contentDirPath: './content',
  documentTypes: [Post],
  disableImportAliasWarning: true,

  async onSuccess(getData) {
    const { allPosts } = await getData()
    const tags = new Set<string>()

    // 收集所有标签
    allPosts.flatMap((post) => post.tags || []).forEach((t) => tags.add(t))

    const tagArray = Array.from(tags).filter(tag => !!tag).sort()

    const jsonPath = '.contentlayer/generated/tagList.json'
    const mjsPath = '.contentlayer/generated/tagList.mjs'

    // 1. 写 JSON
    fs.writeFileSync(jsonPath, JSON.stringify(tagArray, null, 2))

    // 2. 写 MJS
    const mjsContent = `// Auto-generated by Contentlayer on build
export const tagList = ${JSON.stringify(tagArray, null, 2)};
`
    fs.writeFileSync(mjsPath, mjsContent)

    console.log(`✅ Generated ${tagArray.length} tags → ${jsonPath}, ${mjsPath}`)
  },
})
