from typing import Any

MockProject = dict[str, Any]
MockStats = dict[str, Any]
ProjectsPayload = dict[str, Any]

'''
TODO: 接入数据库
'''
MOCK_PROJECTS: list[MockProject] = [
    {
        "id": 1060026581,
        "name": "NextBlog",
        "fullName": "Gemini2035/NextBlog",
        "description": "No description provided",
        "url": "https://github.com/Gemini2035/NextBlog",
        "homepage": "https://gemini2035-github-io.vercel.app",
        "stars": 1,
        "forks": 0,
        "watchers": 1,
        "openIssues": 0,
        "owner": {
            "login": "Gemini2035",
            "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
            "url": "https://github.com/Gemini2035",
        },
        "primaryLanguage": {
            "name": "TypeScript",
            "color": "#3178c6",
        },
        "languageStats": [
            {
                "name": "TypeScript",
                "bytes": 533586,
                "percentage": 92.98158790789424,
                "color": "#3178c6",
            },
            {
                "name": "JavaScript",
                "bytes": 23798,
                "percentage": 4.146990042902301,
                "color": "#f1e05a",
            },
            {
                "name": "CSS",
                "bytes": 8745,
                "percentage": 1.5238855334557786,
                "color": "#563d7c",
            },
            {
                "name": "MDX",
                "bytes": 7733,
                "percentage": 1.3475365157476886,
                "color": "#858585",
            },
        ],
        "contributors": [
            {
                "login": "Gemini2035",
                "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
                "profileUrl": "https://github.com/Gemini2035",
                "contributions": 48,
                "percentage": 100,
            }
        ],
        "topics": [],
        "isFork": False,
        "isArchived": False,
        "isPinned": True,
        "license": None,
        "createdAt": "2025-09-19T09:27:33.000Z",
        "updatedAt": "2025-10-07T12:35:51.000Z",
        "pushedAt": "2025-10-07T12:42:33.000Z",
        "activityScore": 71.80617997398389,
        "displayWeight": 119.9,
        "weight": 10119.9,
    },
    {
        "id": 616380451,
        "name": "Gemini2035.github.io",
        "fullName": "Gemini2035/Gemini2035.github.io",
        "description": "Personal blog",
        "url": "https://github.com/Gemini2035/Gemini2035.github.io",
        "homepage": None,
        "stars": 3,
        "forks": 0,
        "watchers": 3,
        "openIssues": 0,
        "owner": {
            "login": "Gemini2035",
            "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
            "url": "https://github.com/Gemini2035",
        },
        "primaryLanguage": {
            "name": "HTML",
            "color": "#e34c26",
        },
        "languageStats": [
            {
                "name": "HTML",
                "bytes": 6750,
                "percentage": 100,
                "color": "#e34c26",
            }
        ],
        "contributors": [
            {
                "login": "Gemini2035",
                "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
                "profileUrl": "https://github.com/Gemini2035",
                "contributions": 89,
                "percentage": 100,
            }
        ],
        "topics": [],
        "isFork": False,
        "isArchived": False,
        "isPinned": False,
        "license": "Apache License 2.0",
        "createdAt": "2023-03-20T09:24:36.000Z",
        "updatedAt": "2025-09-24T03:37:01.000Z",
        "pushedAt": "2023-12-01T07:18:23.000Z",
        "activityScore": 73.61235994796778,
        "displayWeight": 116.5,
        "weight": 116.5,
    },
    {
        "id": 845906905,
        "name": "AutomationTool",
        "fullName": "Gemini2035/AutomationTool",
        "description": "No description provided",
        "url": "https://github.com/Gemini2035/AutomationTool",
        "homepage": None,
        "stars": 0,
        "forks": 1,
        "watchers": 0,
        "openIssues": 0,
        "owner": {
            "login": "Gemini2035",
            "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
            "url": "https://github.com/Gemini2035",
        },
        "primaryLanguage": {
            "name": "TypeScript",
            "color": "#3178c6",
        },
        "languageStats": [
            {
                "name": "TypeScript",
                "bytes": 23251,
                "percentage": 100,
                "color": "#3178c6",
            }
        ],
        "contributors": [
            {
                "login": "Gemini2035",
                "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
                "profileUrl": "https://github.com/Gemini2035",
                "contributions": 6,
                "percentage": 60,
            },
            {
                "login": "GeorgeZhang2035",
                "avatarUrl": "https://avatars.githubusercontent.com/u/158394211?v=4",
                "profileUrl": "https://github.com/GeorgeZhang2035",
                "contributions": 4,
                "percentage": 40,
            },
        ],
        "topics": [],
        "isFork": False,
        "isArchived": False,
        "isPinned": False,
        "license": None,
        "createdAt": "2024-08-22T06:48:56.000Z",
        "updatedAt": "2024-10-18T02:51:31.000Z",
        "pushedAt": "2024-10-18T02:51:28.000Z",
        "activityScore": 28,
        "displayWeight": 13.2,
        "weight": 13.2,
    },
    {
        "id": 816574184,
        "name": "GeminiDesign",
        "fullName": "Gemini2035/GeminiDesign",
        "description": "No description provided",
        "url": "https://github.com/Gemini2035/GeminiDesign",
        "homepage": None,
        "stars": 0,
        "forks": 0,
        "watchers": 0,
        "openIssues": 0,
        "owner": {
            "login": "Gemini2035",
            "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
            "url": "https://github.com/Gemini2035",
        },
        "primaryLanguage": {
            "name": "TypeScript",
            "color": "#3178c6",
        },
        "languageStats": [
            {
                "name": "TypeScript",
                "bytes": 1461,
                "percentage": 52.83905967450271,
                "color": "#3178c6",
            },
            {
                "name": "JavaScript",
                "bytes": 998,
                "percentage": 36.09403254972875,
                "color": "#f1e05a",
            },
            {
                "name": "HTML",
                "bytes": 306,
                "percentage": 11.066907775768534,
                "color": "#e34c26",
            },
        ],
        "contributors": [
            {
                "login": "Gemini2035",
                "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
                "profileUrl": "https://github.com/Gemini2035",
                "contributions": 4,
                "percentage": 100,
            }
        ],
        "topics": [],
        "isFork": False,
        "isArchived": False,
        "isPinned": False,
        "license": "Apache License 2.0",
        "createdAt": "2024-06-18T02:43:31.000Z",
        "updatedAt": "2024-06-18T06:47:31.000Z",
        "pushedAt": "2025-09-20T11:49:18.000Z",
        "activityScore": 14,
        "displayWeight": 10,
        "weight": 10,
    },
    {
        "id": 751831936,
        "name": "maa-copilot-frontend",
        "fullName": "Gemini2035/maa-copilot-frontend",
        "description": "MAA Copilot Frontend",
        "url": "https://github.com/Gemini2035/maa-copilot-frontend",
        "homepage": "https://prts.plus",
        "stars": 0,
        "forks": 1,
        "watchers": 0,
        "openIssues": 3,
        "owner": {
            "login": "Gemini2035",
            "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
            "url": "https://github.com/Gemini2035",
        },
        "primaryLanguage": {
            "name": "TypeScript",
            "color": "#3178c6",
        },
        "languageStats": [
            {
                "name": "TypeScript",
                "bytes": 810392,
                "percentage": 98.54839121568132,
                "color": "#3178c6",
            },
            {
                "name": "Less",
                "bytes": 6521,
                "percentage": 0.7929916128459533,
                "color": "#858585",
            },
            {
                "name": "CSS",
                "bytes": 2035,
                "percentage": 0.24746786261946255,
                "color": "#563d7c",
            },
            {
                "name": "JavaScript",
                "bytes": 1966,
                "percentage": 0.23907706039796722,
                "color": "#f1e05a",
            },
            {
                "name": "HTML",
                "bytes": 1415,
                "percentage": 0.17207224845530195,
                "color": "#e34c26",
            },
        ],
        "contributors": [
            {
                "login": "guansss",
                "avatarUrl": "https://avatars.githubusercontent.com/u/46285865?v=4",
                "profileUrl": "https://github.com/guansss",
                "contributions": 481,
                "percentage": 55.73580533024334,
            },
            {
                "login": "GalvinGao",
                "avatarUrl": "https://avatars.githubusercontent.com/u/12567059?v=4",
                "profileUrl": "https://github.com/GalvinGao",
                "contributions": 181,
                "percentage": 20.973348783314023,
            },
            {
                "login": "Gemini2035",
                "avatarUrl": "https://avatars.githubusercontent.com/u/76091679?v=4",
                "profileUrl": "https://github.com/Gemini2035",
                "contributions": 15,
                "percentage": 1.738122827346466,
            },
        ],
        "topics": [],
        "isFork": True,
        "isArchived": False,
        "isPinned": False,
        "license": None,
        "createdAt": "2024-02-02T12:29:16.000Z",
        "updatedAt": "2025-06-01T04:38:05.000Z",
        "pushedAt": "2025-10-07T16:53:24.000Z",
        "activityScore": 42,
        "displayWeight": 71.3,
        "weight": 71.3,
    },
]

MOCK_STATS: MockStats = {
    "totalProjects": len(MOCK_PROJECTS),
    "totalStars": sum(project["stars"] for project in MOCK_PROJECTS),
    "totalForks": sum(project["forks"] for project in MOCK_PROJECTS),
    "languageDistribution": [
        {"name": "TypeScript", "bytes": 4, "percentage": 57.1, "color": "#3178c6"},
        {"name": "HTML", "bytes": 2, "percentage": 28.6, "color": "#e34c26"},
        {"name": "Python", "bytes": 1, "percentage": 14.3, "color": "#3572A5"},
    ],
    "categoryDistribution": {
        "featured": 1,
        "active": 2,
        "stable": 1,
        "completed": 3,
        "archived": 0,
        "fork": 2,
        "learning": 0,
    },
    "activeProjects": 2,
    "archivedProjects": 0,
    "ownedStats": {
        "count": 5,
        "stars": 128,
        "forks": 32,
        "languages": 3,
    },
    "contributedStats": {
        "count": 2,
        "stars": 12350,
        "forks": 2458,
        "languages": 2,
    },
}
