export { default as Waterfall } from './Waterfall'
export { default as BasicInfoSection } from './BasicInfoSection'
export { default as SkillsSection } from './SkillsSection'
export { default as WorkExperienceSection } from './WorkExperienceSection'
export { default as EducationSection } from './EducationSection'
export { default as AchievementsSection } from './AchievementsSection'
export { default as TechStackSection } from './TechStackSection'
export { default as FeaturesSection } from './FeaturesSection'
