"""create project and embedding tables

Revision ID: 08e665ccfef0
Revises: 
Create Date: 2026-05-22 22:36:06.662409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e665ccfef0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'embedding_model')
    )
    op.create_index('ix_embedding_source', 'embedding', ['source_type', 'source_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('owner_login', sa.String(length=255), nullable=False),
    sa.Column('owner_avatar_url', sa.Text(), nullable=False),
    sa.Column('owner_url', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('primary_language_name', sa.String(length=100), nullable=True),
    sa.Column('primary_language_color', sa.String(length=20), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contributors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_score', sa.Float(), nullable=True),
    sa.Column('display_weight', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_full_name'), 'project', ['full_name'], unique=True)
    op.create_index(op.f('ix_project_github_updated_at'), 'project', ['github_updated_at'], unique=False)
    op.create_index(op.f('ix_project_is_archived'), 'project', ['is_archived'], unique=False)
    op.create_index(op.f('ix_project_is_fork'), 'project', ['is_fork'], unique=False)
    op.create_index(op.f('ix_project_is_pinned'), 'project', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_project_owner_login'), 'project', ['owner_login'], unique=False)
    op.create_index(op.f('ix_project_primary_language_name'), 'project', ['primary_language_name'], unique=False)
    op.create_index(op.f('ix_project_weight'), 'project', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_weight'), table_name='project')
    op.drop_index(op.f('ix_project_primary_language_name'), table_name='project')
    op.drop_index(op.f('ix_project_owner_login'), table_name='project')
    op.drop_index(op.f('ix_project_is_pinned'), table_name='project')
    op.drop_index(op.f('ix_project_is_fork'), table_name='project')
    op.drop_index(op.f('ix_project_is_archived'), table_name='project')
    op.drop_index(op.f('ix_project_github_updated_at'), table_name='project')
    op.drop_index(op.f('ix_project_full_name'), table_name='project')
    op.drop_table('project')
    op.drop_index('ix_embedding_source', table_name='embedding')
    op.drop_table('embedding')
    # ### end Alembic commands ###
