"""empty message

Revision ID: 6622961ab794
Revises: add8f2eb3711
Create Date: 2026-05-28 14:53:22.554839

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '6622961ab794'
down_revision: Union[str, Sequence[str], None] = 'add8f2eb3711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
