"""empty message

Revision ID: 872ef668f4e6
Revises: 9d4b2d1a8c0f
Create Date: 2026-05-25 16:14:07.776172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872ef668f4e6'
down_revision: Union[str, Sequence[str], None] = '9d4b2d1a8c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_tag_name'), 'blog_tag', ['name'], unique=True)
    op.create_table('blog_post',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['site_language.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blog_post_is_featured', 'blog_post', ['is_featured'], unique=False)
    op.create_index('ix_blog_post_language_id', 'blog_post', ['language_id'], unique=False)
    op.create_table('blog_post_tag',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post_tag')
    op.drop_index('ix_blog_post_language_id', table_name='blog_post')
    op.drop_index('ix_blog_post_is_featured', table_name='blog_post')
    op.drop_table('blog_post')
    op.drop_index(op.f('ix_blog_tag_name'), table_name='blog_tag')
    op.drop_table('blog_tag')
    # ### end Alembic commands ###
