"""empty message

Revision ID: add8f2eb3711
Revises: f399fc0189c6
Create Date: 2026-05-28 14:43:37.338820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add8f2eb3711'
down_revision: Union[str, Sequence[str], None] = 'f399fc0189c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table("static_content_category"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_content_category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['static_content_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_static_content_category_key', 'static_content_category', ['key'], unique=False)
    op.create_index('ix_static_content_category_parent_id', 'static_content_category', ['parent_id'], unique=False)
    op.create_index('ix_static_content_category_sort_order', 'static_content_category', ['sort_order'], unique=False)
    op.add_column('static_content', sa.Column('category_id', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('uq_static_content_key_global'), table_name='static_content', postgresql_where='(locale_id IS NULL)')
    op.create_index('uq_static_content_key_global', 'static_content', ['category_id', 'key'], unique=True, postgresql_where=sa.text('locale_id IS NULL'))
    op.drop_index(op.f('uq_static_content_key_locale'), table_name='static_content', postgresql_where='(locale_id IS NOT NULL)')
    op.create_index('uq_static_content_key_locale', 'static_content', ['category_id', 'key', 'locale_id'], unique=True, postgresql_where=sa.text('locale_id IS NOT NULL'))
    op.create_index('ix_static_content_category_id', 'static_content', ['category_id'], unique=False)
    op.create_foreign_key(None, 'static_content', 'static_content_category', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'static_content', type_='foreignkey')
    op.drop_index('ix_static_content_category_id', table_name='static_content')
    op.drop_index('uq_static_content_key_locale', table_name='static_content', postgresql_where=sa.text('locale_id IS NOT NULL'))
    op.create_index(op.f('uq_static_content_key_locale'), 'static_content', ['key', 'locale_id'], unique=True, postgresql_where='(locale_id IS NOT NULL)')
    op.drop_index('uq_static_content_key_global', table_name='static_content', postgresql_where=sa.text('locale_id IS NULL'))
    op.create_index(op.f('uq_static_content_key_global'), 'static_content', ['key'], unique=True, postgresql_where='(locale_id IS NULL)')
    op.drop_column('static_content', 'category_id')
    op.drop_index('ix_static_content_category_sort_order', table_name='static_content_category')
    op.drop_index('ix_static_content_category_parent_id', table_name='static_content_category')
    op.drop_index('ix_static_content_category_key', table_name='static_content_category')
    op.drop_table('static_content_category')
    # ### end Alembic commands ###
