"""empty message

Revision ID: f028adffed56
Revises: 9c4f8d1e2a73
Create Date: 2026-05-28 16:04:52.343469

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'f028adffed56'
down_revision: Union[str, Sequence[str], None] = '9c4f8d1e2a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
