"""empty message

Revision ID: f399fc0189c6
Revises: 960c6a9a04a4
Create Date: 2026-05-27 17:15:33.790226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f399fc0189c6'
down_revision: Union[str, Sequence[str], None] = '960c6a9a04a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config_category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['site_config_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_site_config_category_key', 'site_config_category', ['key'], unique=False)
    op.create_index('ix_site_config_category_parent_id', 'site_config_category', ['parent_id'], unique=False)
    op.create_index('ix_site_config_category_sort_order', 'site_config_category', ['sort_order'], unique=False)
    op.add_column('site_setting', sa.Column('category_id', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_site_setting_parent_id'), table_name='site_setting')
    op.drop_constraint(op.f('site_setting_key_key'), 'site_setting', type_='unique')
    op.create_index('ix_site_setting_category_id', 'site_setting', ['category_id'], unique=False)
    op.create_unique_constraint('uq_site_setting_category_key', 'site_setting', ['category_id', 'key'])
    op.drop_constraint(op.f('site_setting_parent_id_fkey'), 'site_setting', type_='foreignkey')
    op.create_foreign_key(None, 'site_setting', 'site_config_category', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('site_setting', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_setting', sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'site_setting', type_='foreignkey')
    op.create_foreign_key(op.f('site_setting_parent_id_fkey'), 'site_setting', 'site_setting', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_site_setting_category_key', 'site_setting', type_='unique')
    op.drop_index('ix_site_setting_category_id', table_name='site_setting')
    op.create_unique_constraint(op.f('site_setting_key_key'), 'site_setting', ['key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_site_setting_parent_id'), 'site_setting', ['parent_id'], unique=False)
    op.drop_column('site_setting', 'category_id')
    op.drop_index('ix_site_config_category_sort_order', table_name='site_config_category')
    op.drop_index('ix_site_config_category_parent_id', table_name='site_config_category')
    op.drop_index('ix_site_config_category_key', table_name='site_config_category')
    op.drop_table('site_config_category')
    # ### end Alembic commands ###
