export { default as HomeSectionSkeleton } from './HomeSectionSkeleton'
export type { HomeSectionSkeletonProps } from './HomeSectionSkeleton'
export { default as BlogSection } from './BlogSection/index'
export { default as AboutSection } from './AboutSection/index'
export { default as ProjectsSection } from './ProjectsSection/index'
export { default as ResourcesSection } from './ResourcesSection/index'
export { default as SectionSwitch } from './SectionSwitch'
export type { SectionSwitchProps } from './SectionSwitch'
