/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projects */
        get: operations["get_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Detail */
        get: operations["get_project_detail_api_projects__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handle Http Get */
        get: operations["handle_http_get_api_graphql_get"];
        put?: never;
        /** Handle Http Post */
        post: operations["handle_http_post_api_graphql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[ProjectDetailPayload] */
        ApiResponse_ProjectDetailPayload_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data: components["schemas"]["ProjectDetailPayload"];
        };
        /** ApiResponse[ProjectsPayload] */
        ApiResponse_ProjectsPayload_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data: components["schemas"]["ProjectsPayload"];
        };
        /** ContributorStat */
        ContributorStat: {
            /** Login */
            login: string;
            /** Avatarurl */
            avatarUrl: string;
            /** Profileurl */
            profileUrl: string;
            /** Contributions */
            contributions: number;
            /** Name */
            name?: string | null;
            /** Percentage */
            percentage?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LanguageStat */
        LanguageStat: {
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Percentage */
            percentage: number;
            /** Bytes */
            bytes: number;
        };
        /** PrimaryLanguage */
        PrimaryLanguage: {
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Stars */
            stars: number;
            /** Forks */
            forks: number;
            primaryLanguage?: components["schemas"]["PrimaryLanguage"] | null;
            /** Topics */
            topics: string[];
            /** Isfork */
            isFork: boolean;
            /** Isarchived */
            isArchived: boolean;
            /** Ispinned */
            isPinned: boolean;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
            /** Pushedat */
            pushedAt: string;
            /** Weight */
            weight?: number | null;
            /** Contributorcount */
            contributorCount: number;
            /** Fullname */
            fullName: string;
            /** Url */
            url: string;
            /** Homepage */
            homepage?: string | null;
            /** Watchers */
            watchers: number;
            /** Openissues */
            openIssues: number;
            owner: components["schemas"]["ProjectOwner"];
            /** Languages */
            languages: {
                [key: string]: number;
            };
            /** Languagestats */
            languageStats: components["schemas"]["LanguageStat"][];
            /** Contributors */
            contributors: components["schemas"]["ContributorStat"][];
            /**
             * Istemplate
             * @default false
             */
            isTemplate: boolean;
            /**
             * Isprivate
             * @default false
             */
            isPrivate: boolean;
            /**
             * Isfeatured
             * @default false
             */
            isFeatured: boolean;
            /** License */
            license?: string | null;
            /**
             * Defaultbranch
             * @default main
             */
            defaultBranch: string;
            /** Activityscore */
            activityScore?: number | null;
            /** Displayweight */
            displayWeight?: number | null;
        };
        /** ProjectDetailPayload */
        ProjectDetailPayload: {
            project: components["schemas"]["ProjectDetail"];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "mock" | "database";
        };
        /** ProjectListItem */
        ProjectListItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Stars */
            stars: number;
            /** Forks */
            forks: number;
            primaryLanguage?: components["schemas"]["PrimaryLanguage"] | null;
            /** Topics */
            topics: string[];
            /** Isfork */
            isFork: boolean;
            /** Isarchived */
            isArchived: boolean;
            /** Ispinned */
            isPinned: boolean;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
            /** Pushedat */
            pushedAt: string;
            /** Weight */
            weight?: number | null;
            /** Contributorcount */
            contributorCount: number;
        };
        /** ProjectOwner */
        ProjectOwner: {
            /** Login */
            login: string;
            /** Avatarurl */
            avatarUrl: string;
            /** Url */
            url: string;
        };
        /** ProjectStats */
        ProjectStats: {
            /** Totalprojects */
            totalProjects: number;
            /** Totalstars */
            totalStars: number;
            /** Totalforks */
            totalForks: number;
            /** Languagedistribution */
            languageDistribution: components["schemas"]["LanguageStat"][];
            /** Categorydistribution */
            categoryDistribution: {
                [key: string]: number;
            };
            /** Activeprojects */
            activeProjects: number;
            /** Archivedprojects */
            archivedProjects: number;
            ownedStats?: components["schemas"]["ProjectStatsGroup"] | null;
            contributedStats?: components["schemas"]["ProjectStatsGroup"] | null;
        };
        /** ProjectStatsGroup */
        ProjectStatsGroup: {
            /** Count */
            count: number;
            /** Stars */
            stars: number;
            /** Forks */
            forks: number;
            /** Languages */
            languages: number;
        };
        /** ProjectsPayload */
        ProjectsPayload: {
            /** Projects */
            projects: components["schemas"]["ProjectListItem"][];
            stats: components["schemas"]["ProjectStats"];
            rateLimit?: components["schemas"]["RateLimit"] | null;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "mock" | "database";
        };
        /** RateLimit */
        RateLimit: {
            /** Limit */
            limit: number;
            /** Remaining */
            remaining: number;
            /** Resetat */
            resetAt: string;
            /** Used */
            used: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectsPayload_"];
                };
            };
        };
    };
    get_project_detail_api_projects__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectDetailPayload_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    handle_http_get_api_graphql_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The GraphiQL integrated development environment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found if GraphiQL or query via GET are not enabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    handle_http_post_api_graphql_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
