export {
  POST_DETAIL_QUERY,
  RELATED_POSTS_QUERY,
  POST_LIST_QUERY,
  FEATURED_POSTS_QUERY,
  RECENT_POSTS_QUERY,
  type PostDetailResult,
  type RelatedPostsResult,
  type PostListResult,
  type PostListMetaData,
  type FeaturedPostsResult,
  type RecentPostsResult,
  mapGqlPostToBlogPost,
  mapGqlRelatedPostToBlogPost,
  mapGqlListPostToBlogPost,
} from './queries'
